-- AUTHOR: 'WANDEX/nvim-conf'
-- spec 'onsails/lspkind.nvim'

-- copied from lspkind src, but, added a modified *_mod kinds!
-- added extra ' ' after each icon, to properly fit without cutting the symbol.
-- meant for the nerd fonts with explicitly bigger icons size! ~2 term cols width.
local kind_presets = {
  default = {
    Text = "󰉿 ",
    Method = "󰆧 ",
    Function = "󰊕 ",
    Constructor = " ",
    Field = "󰜢 ",
    Variable = "󰀫 ",
    Class = "󰠱 ",
    Interface = " ",
    Module = " ",
    Property = "󰜢 ",
    Unit = "󰑭 ",
    Value = "󰎠 ",
    Enum = " ",
    Keyword = "󰌋 ",
    Snippet = " ",
    Color = "󰏘 ",
    File = "󰈙 ",
    Reference = "󰈇 ",
    Folder = "󰉋 ",
    EnumMember = " ",
    Constant = "󰏿 ",
    Struct = "󰙅 ",
    Event = " ",
    Operator = "󰆕 ",
    TypeParameter = " ",
  },
  codicons = {
    Text = " ",
    Method = " ",
    Function = " ",
    Constructor = " ",
    Field = " ",
    Variable = " ",
    Class = " ",
    Interface = " ",
    Module = " ",
    Property = " ",
    Unit = " ",
    Value = " ",
    Enum = " ",
    Keyword = " ",
    Snippet = " ",
    Color = " ",
    File = " ",
    Reference = " ",
    Folder = " ",
    EnumMember = " ",
    Constant = " ",
    Struct = " ",
    Event = " ",
    Operator = " ",
    TypeParameter = " ",
  },
  codicons_mod = {
    Text = " ",
    Method = " ",
    Function = "󰊕 ", -- mod
    Constructor = "󰅲 ", -- mod
    Field = " ",
    Variable = " ",
    Class = " ",
    Interface = " ",
    Module = " ",
    Property = " ",
    Unit = " ",
    Value = " ",
    Enum = " ",
    Keyword = " ",
    Snippet = " ",
    Color = " ",
    File = " ",
    Reference = "󰈇 ", -- mod
    Folder = " ",
    EnumMember = " ",
    Constant = " ",
    Struct = " ",
    Event = " ",
    Operator = " ",
    TypeParameter = " ",
  },
}

return {
  'onsails/lspkind.nvim',
  lazy = false,
  opts = {
    mode = 'symbol',
    -- preset = 'codicons',
    symbol_map = kind_presets.codicons_mod,
  },
}
